export { default as Header } from "./Header/Header";
export { default as Body } from "./Body/Body";
export { default as Shimmer } from "./Shimmer/Shimmer";
export { default as Carousel } from "./Carousel/Carousel";
export { default as AboutUs } from "./AboutUs/AboutUs";
export { default as ContactUS } from "./ContactUs/ContactUs";
export { default as Error } from "./Error/Error";
export { default as Cart } from "./Cart/Cart";
export { default as RestaurantMenu } from "./RestaurantMenu/RestaurantMenu";
